name: Build CV and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-texlive

    steps:
      - uses: actions/checkout@v4

      - name: compile latex CV
        run: pdflatex main.tex

      - name: Archive PDF
        run: |
          mkdir -p output
          mv main.pdf output/

      # Get the latest tag and increment version
      - name: Increment version
        id: version
        run: |
          # 获取最新的 tag，默认从 v0.0.0 开始
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $latest_tag"

          # 解析最新的版本号
          IFS='.' read -r -a version_parts <<< "${latest_tag//v/}"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}

          # 递增 patch 版本号
          new_patch=$((patch+1))
          new_tag="v${major}.${minor}.${new_patch}"

          echo "New version: $new_tag"
          echo "::set-output name=version::$new_tag"

      # Create a release and upload PDF
      - name: Upload PDF to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.version }}
          name: "Release ${{ steps.version.outputs.version }}"
          artifacts: output/main.pdf
