name: Build LaTeX document

# 当发生 push 或 pull request 时触发工作流
on:
  push:
    branches:
      - main
  pull_request:

# 定义任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: compile latex CV
        uses: pdflatex main.tex